services:
  app:
    image: bonkboykz/aws-example:latest
    container_name: app
    restart: always
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2.4.3
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
